version: '2'
services:
  logstash:
    start_on_create: true
    ${scale}
    health_check:
      port: 9600
      interval: 30000
      unhealthy_threshold: 3
      healthy_threshold: 3
      response_timeout: 5000
      strategy: recreate
      initializing_timeout: 120000
      reinitializing_timeout: 120000
      request_line: GET / HTTP/1.1